name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test
    - name: Run all examples
      run: sbt runAll
    - name: Check formatting
      run: sbt 'scalafmtSbtCheck; scalafmtCheck'
